### ISSUE TITLE
Allow pilot to set their Competion Class

### ISSUE THREAD

**Issue by DawsonLeBrown** [geeksville/Gaggle#35]
At the moment, gaggle is hard coded to set the "Klasse" parameter to "3"  which is Paraglider (open) when it submits the tracklog to leonardo. This forces non PG Open pilots to need to edit the submittion on their OLC after it's been submitted.

The pilot should be allowed to set their competition class by choosing the right one from a list prior to submitting the tracklog.

I have made the necessary changes to the code for this feature, but am unsure by what method  you'd like me to share my code changes. 

I could submit them directly with GIT - but would probably need authorization to do so, or I could send the changed files. A little translation work will still need to be done for de & hu to complete the mod.

Dawson

**Comment by sletuffe** [comment]
Hi dawson, what I have done to add my proposed patches was like this :
Following this to fork gaggle : http://help.github.com/fork-a-repo/
It will create a space for you where you can commit changes with git and test things, or let other test and review what you have done brefore merging it to the master branch of geeksville

Then, by using the "pull request" button on your fork, the gaggle author will be notified (and me as well) and can review and/or test your changes and then merge them back to the "upstream" gaggle.

I guess there might be some quicker way so that we all commit to the same repo, but the forking way looks safer

**Comment by DawsonLeBrown** [comment]
Thanks sly.

I've now checked in my changes.
