### ISSUE TITLE
WPT import should use altitude unit display preference

### ISSUE THREAD

**Issue by dylanbuli** [geeksville/Gaggle#6]
When importing a WPT with altitude in feet, Gaggle will always assume that it is in meters. Perhaps use the preference when there are no units specified.

**Comment by geeksville** [comment]
Hmm - I'm not so sure this is a good idea.  I think the various WPT file formats specify the units as meters.  Do you have an example of a file that was not correctly parsed?  If so, can you attach it to the bug?

**Comment by dylanbuli** [comment]
On more investigation, it looks like the soaring way point databases from the Waypoint Exchange depend on the area. In the US they are in feet, in the Alps, its in meters.  So obeying the preference during import might make sense (if there is no other indication of standard used in the .wpt.)
http://soaringweb.org/TP/NA.html#CO
http://soaringweb.org/TP/Alps_out

This site might be useful for WPT examples for you too.

**Comment by geeksville** [comment]
Thank you for the report Dylan.  I looked at the files and finally found a spec for CompeGPS and Oziexplorer format files - they both call for feet, so that's what I'll start using.  For the legacy simple wpt format, those seem to be in meters both in Europe and the US.  Please let me know how this works out for you.

**Comment by dylanbuli** [comment]
Fixed in .81, thanks!
